// default package
// Generated 11-17-2016 01:10:07 AM by Hibernate Tools 5.2.0.Beta1
package com.sv.udb.modelo;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alumnos generated by hbm2java
 */
@Entity
@Table(name = "alumnos", catalog = "struts")
public class Alumnos implements java.io.Serializable {

	private static final long serialVersionUID = -8767337896773261247L;
	
	private Integer codiAlum;
	private String nombAlum;
	private String apelAlum;
	private Date fechNaciAlum;
	private String mailAlum;
	private String teleAlum;
	private String direAlum;
	private char geneAlum;
	private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

	public Alumnos() {
	}

	public Alumnos(String nombAlum, String apelAlum, Date fechNaciAlum, String mailAlum, String teleAlum,
			String direAlum, char geneAlum) {
		this.nombAlum = nombAlum;
		this.apelAlum = apelAlum;
		this.fechNaciAlum = fechNaciAlum;
		this.mailAlum = mailAlum;
		this.teleAlum = teleAlum;
		this.direAlum = direAlum;
		this.geneAlum = geneAlum;
	}

	public Alumnos(String nombAlum, String apelAlum, Date fechNaciAlum, String mailAlum, String teleAlum,
			String direAlum, char geneAlum, Set<Usuarios> usuarioses) {
		this.nombAlum = nombAlum;
		this.apelAlum = apelAlum;
		this.fechNaciAlum = fechNaciAlum;
		this.mailAlum = mailAlum;
		this.teleAlum = teleAlum;
		this.direAlum = direAlum;
		this.geneAlum = geneAlum;
		this.usuarioses = usuarioses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codi_alum", unique = true, nullable = false)
	public Integer getCodiAlum() {
		return this.codiAlum;
	}

	public void setCodiAlum(Integer codiAlum) {
		this.codiAlum = codiAlum;
	}

	@Column(name = "nomb_alum", nullable = false, length = 100)
	public String getNombAlum() {
		return this.nombAlum;
	}

	public void setNombAlum(String nombAlum) {
		this.nombAlum = nombAlum;
	}

	@Column(name = "apel_alum", nullable = false, length = 100)
	public String getApelAlum() {
		return this.apelAlum;
	}

	public void setApelAlum(String apelAlum) {
		this.apelAlum = apelAlum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fech_naci_alum", nullable = false, length = 0)
	public Date getFechNaciAlum() {
		return this.fechNaciAlum;
	}

	public void setFechNaciAlum(Date fechNaciAlum) {
		this.fechNaciAlum = fechNaciAlum;
	}

	@Column(name = "mail_alum", nullable = false, length = 100)
	public String getMailAlum() {
		return this.mailAlum;
	}

	public void setMailAlum(String mailAlum) {
		this.mailAlum = mailAlum;
	}

	@Column(name = "tele_alum", nullable = false, length = 20)
	public String getTeleAlum() {
		return this.teleAlum;
	}

	public void setTeleAlum(String teleAlum) {
		this.teleAlum = teleAlum;
	}

	@Column(name = "dire_alum", nullable = false, length = 200)
	public String getDireAlum() {
		return this.direAlum;
	}

	public void setDireAlum(String direAlum) {
		this.direAlum = direAlum;
	}

	@Column(name = "gene_alum", nullable = false, length = 1)
	public char getGeneAlum() {
		return this.geneAlum;
	}

	public void setGeneAlum(char geneAlum) {
		this.geneAlum = geneAlum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alumnos")
	public Set<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}

}
